config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: :about
  get "search_book" => "books#search_book"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :new]
  resources :categorys, expect: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :categories, through: :book_categories, dependent: :destroy
  has_many :book_categories, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { in: 1..200 }

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :rating, -> {order(star: :desc)}
  scope :rating_bad, -> {order(star: :asc)}

  def self.search(search_word)
    Book.where(["category LIKE ?", "#{search_word}"])
  end

end

app/models/book_category.rb
class BookCategory < ApplicationRecord
 belongs_to :book
 belongs_to :category

 validates :book_id,presence:true
 validates :category_id,presence:true

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
 belongs_to :user
 belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
 
 validates :name,presence:true,length:{maxmum:50}
 has_many :books, through: :book_categories
 has_many book_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def get_imageuser
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

   def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

 def create
  book = Book.find(params[:book_id])
  comment = current_user.book_comments.new(comment_params)
  comment.book_id = book.id
  comment.save
  redirect_to book_path(book)
 end

 private

 def comment_params
  params.require(:book_comment).permit(:comment)
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all

    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:rating]
      @books = Book.rating
    elsif params[:rating_bad]
      @books = Book.rating_bad
    else
      @books = Book.all
    end

    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      flash[:alert] = "error"
      @books = Book.all
      render :edit
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end


  def search_book
    @book = Book.new
    @books = Book.search(params[:keyword])
    @keyword = params[:keyword]
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  
  
  def index
    @category = Category.new
    @categories = Category.all
    
  end

  def create
    @category = Category.new(category_params)
    if category.save
      redirect_to categories_path
    else
      @categories = category.all
      render "index"
    end
  end
  
  def edit
  end
  
  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render "edit"
    end
  end
  
  def destroy
    @category.destroy
    redirect_to categories_path
  end
  
  private
  
  def set_category
    @category = Category.find(params[:id])
  end
  
  def category_params
    params.require(:category).permit(name)
  ends
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      flash[:alart] = "is too short (minimum is 2 characters)"
      @users = User.all
      render "edit"
    end
  end

  def create
    @user = User.new(user_params)
    if @usre.save
      redirect_to usre_path(@user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面に遷移できません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_raty.html.erb
 <script>
  $("#star1").empty();
   $('#star1').raty({
     size     : 38,
     starOff:  '<%= asset_path('star-off.png') %>',
     starOn : '<%= asset_path('star-on.png') %>',
     starHalf: '<%= asset_path('star-half.png') %>',
     scoreName: 'book[star]',
     half: true,
   });
 </script>

app/views/books/_raty2.html.erb
 <script>
  $("#book-rat-<%= book.id %>").empty();
   $('#book-rat-<%= book.id %>').raty({      //.idでどの評価であるかを取得
     size: 38,
     starOff:  '<%= asset_path('star-off.png') %>',
     starOn : '<%= asset_path('star-on.png') %>',
     starHalf: '<%= asset_path('star-half.png') %>',
     half: true,
     readOnly: true,                             //readOnlyオプションで読み込み専用とする。編集できない。
     score: <%= book.star %>,              //scoreオプションで評価内容を取得
   });
 </script>

app/views/books/_searchform.html.erb
<div class="search_form">
 <%= form_with url: search_book_path, method: :get, local: true do |f| %>
 <%= f.text_field :keyword %>
 <%= f.submit "検索" %>
 <% end %>
</div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
    <%= form_with model: @book do |f| %>

    <div class="form-group">
     <label for="book-title">Title</label>
     <%= f.text_field :title,class: "form-control book_title" %>
    </div>

    <div class="form-group">
     <label for="book-body">Opinion</label>
    <%= f.text_area :body,class: "form-control book_body" %>
    </div>

    <div class="form-group">
     <%= f.submit "Update Book",class: "btn btn-success" %>
    </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %>
    <%= "|" %>
    <%= link_to "Back", books_path %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render "users/user", user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h7>タグ検索機能</h7>
      <%= render "books/searchform", book: @book %>
    <h2>Books</h2>
    <p>
      <%= link_to "新しい順", books_path(latest: "true"), class: "btn btn-success" %>
      | <%= link_to "古い順", books_path(old: "true"), class: "btn btn-info" %>
      | <%= link_to "評価の高い順", books_path(rating: "true"), class: "btn btn-dark" %>
      | <%= link_to "評価の悪い順", books_path(rating_bad: "true"), class: "btn btn-warning" %>
    </p>
    <table class="table table-hover table-inverse">
      <thred>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
      </thred>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
          <td>
            <div class="star-group">
            <div class="detail-rating", id="book-rat-<%= book.id %>"></div>
            <div class="eval-star"><%= book.star %>/5点</div>
            <%= render "raty2", book: book %>
             <td><%= l book.created_at %></td>
             <td><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id), data:{"turbolinks" => false} %><p></td>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
     <%= render "users/user", user: @user, book: @book %>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
      

       <table class="table table-hover table-inverse">
         <thred>
           <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th colspan="3"></th>
           </tr>
         </thred>
         <tbody>
           <% @books.each do |book| %>
           <tr>
             <td>
                <%= image_tag book.current_user.get_profile_image(100,100) %></br>
             </td>
             <td>
                <%= book.current_user.title %>
             </td>
             <td>
                 <%= book.current_user.body %>
             </td>
           </tr>
           <% end %>
         </tbody>
       </table>
     </div>
  </div>
</div>





<h1>画像投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.file_field :title %>
    <h4>Opinion</h4>
      <%= f.text_field :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/search_book.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-8 offset-md-1">
   <h2>Books category search</h2>
   <table>
    <thred>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
     </tr>
    </thred>
   <tbody>
   <% @books.each do |book| %>
    <tr>
     <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %></td>
     <td><%= link_to book_path(book.id) %><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
   <% end %>
    </tr>
   </tbody>
  </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <%= render "users/user", user: @user, book: @book_new %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to image_tag @book.user.get_profile_image(100,100) %></br>
              <%= link_to @user.name, user_path(@user.id) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id), data:{"turbolinks" => false} %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <%= @book.category %>
            </td>
            <td>
            <div class="star-group">
              <div class="detail-rating", id="book-rat-<%= @book.id %>"></div>
              <div class="eval-star"><%= @book.star %>/5点</div>
              <%= render "raty2", book: @book %>
            </div>
            </td>
              <div class="comment_container">
              <h3>コメント件数: <%= @book.book_comments.count %></h3>
              <table>
                <% @book_comments.each do |book_comment| %>
                <tr><td><%= book_comment.user.name %></td></tr>
                <tr><th><%= book_comment.created_at.strftime("%Y/%m/%d") %></th></tr>
                <tr><th><%= book_comment.comment %></th></tr>
                <% end %>
                </tr>
              </div>
              <div>
                <%= form_with model: [@book, @comment] do |f| %>
                  <%= f.text_area :comment, rows: "5", placeholder: "コメントをここに" %></br>
                  <%= f.submit "コメントする" %>
                <% end %>
              </div>
            </td>
            <td>
              <% if @user.id == current_user.id %>
              <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path, method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
  <h1 class="px-3 mx-auto">Welcome to  <i class="fas fa-book"></i><strong>Booekrs</strong>!</h1>
 </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="contaikner">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcom to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
            <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block md-3 sign_in", method: :post %>
                </div>
                <div class="row">
                    <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                </div>
                <div class="row">
                    <%= link_to "Sign up", new_user_registration_path,class: "btn btn-success btn-sm btn-block sign_up" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_user.html.erb
  <div class="col-md-3">
   <% if book.errors.any? %>
    <%= book.errors.count %>error
    <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>

    <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        <th></th>
        </tr>
      </tbody>
    </table>
    <% if user.name != "guestuser" %>
    <div class="row">
      <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block edit_user_11572" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>

    <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local: true do |f| %>
      <div class="form-group">
        <lavel for="book_title">Title</lavel></br>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <lavel for="book_body">Opinion</lavel></br>
        <%= f.text_area :body %></br>
      </div>
      <div class="form-group">
      <%= form_with model: @book, local: true do |f| %>
        <%= f.label :category,"Tag", class:"category-title" %></br>
        <%= f.text_field :category %>
      </div>
      <%= form_with(model: @book, local: true) do |f| %>
      <div class="star-form-group" id="star1">               <%#id要素の付与がポイント%>
        <%= f.label :star,'Rate', class:'star-title' %>　<%#保存したいカラムの指定%>
        <%= render "books/raty" %></br>
      <br>
      <%= f.submit "Create Book",class: "btn btn-success" %>
      <% end %>
      </div>
        <% end %>
        <% end %>
      <% end %>
  </div>

app/views/users/edit.html.erb
<p id ="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>
      <%= form_with model: @user do |f| %>
      <div class="form-group">
      <label for="input name">Name</label>
      <%= f.text_field :name,class: "form-control name", autofocus: true, id:"inputName" %>
     </div>

      <div class="form-group">
       <label for="Image">Image</label>
       <%= f.file_field :profile_image,class: "form-control-file user_image", placeholder: "ファイルを選択", accept: "image/*" %>
      </div>

      <div class="form-group">
       <label for="input introduction">introduction</label>
       <%= f.text_area :introduction,class: "form-control introduction" %>
      </div>

     <div class="form-group">
      <%= f.submit "Update User",class: "btn btn-secondary" %>
     </div>
     <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
    <div class="row">
        <%= render "user", user: @user, book: @book %>
            <div class="col-md-8 offset-md-1">
                <h2>Users</h2>
                <table class="table">
                    <thred>
                        <tr>
                            <th>image</th>
                            <th>name</th>
                            <th colspan="3"></th>
                        </tr>
                    </thred>
                    <tbody>
                        <% @users.each do |user| %>
                        <tr>
                            <td>
                                <%= image_tag @user.get_profile_image(100,100) %>
                            </td>
                            <td>
                                <%= user.name %>
                            </td>
                            <td>
                                <%= link_to "Show", user_path(user) %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
    </div>
</div>

app/views/users/show.html.erb
 <p id="notice"></p>
 <div class="container px-5 px-sm-0">
  <div class="row">
 <%= render "user", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
    <table class="table table-hover table-inverse">
       <thred>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
         </tr>
       </thred>
       <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
           <div class="star-group">
            <div class="detail-rating", id="book-rat-<%= book.id %>"></div>
            <div class="eval-star"><%= book.star %>/5点</div>
            <%= render "books/raty2", book: book %>
           <td><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %><p></td>
           </td>
        </tr>
        <% end %>
       </tbody>
    </table>
    </div>
  </div>
 </div>