config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: :about
  get "search_book" => "books#search_book"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :new]
  resources :categorys, expect: [:new, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :categories, through: :book_categories, dependent: :destroy
  has_many :book_categories, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { in: 1..200 }

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :rating, -> {order(star: :desc)}
  scope :rating_bad, -> {order(star: :asc)}

  def self.search(search_word)
    Book.where(["category LIKE ?", "#{search_word}"])
  end

end

app/models/book_category.rb
class BookCategory < ApplicationRecord
 belongs_to :book
 belongs_to :category

 validates :book_id,presence:true
 validates :category_id,presence:true

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
 belongs_to :user
 belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
 
 validates :name,presence:true,length:{maxmum:50}
 has_many :books, through: :book_categories
 has_many book_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def get_imageuser
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

   def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

 def create
  book = Book.find(params[:book_id])
  comment = current_user.book_comments.new(comment_params)
  comment.book_id = book.id
  comment.save
  redirect_to book_path(book)
 end

 private

 def comment_params
  params.require(:book_comment).permit(:comment)
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all

    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:rating]
      @books = Book.rating
    elsif params[:rating_bad]
      @books = Book.rating_bad
    else
      @books = Book.all
    end

    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      flash[:alert] = "error"
      @books = Book.all
      render :edit
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end


  def search_book
    @book = Book.new
    @books = Book.search(params[:keyword])
    @keyword = params[:keyword]
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  
  
  def index
    @category = Category.new
    @categories = Category.all
    
  end

  def create
    @category = Category.new(category_params)
    if category.save
      redirect_to categories_path
    else
      @categories = category.all
      render "index"
    end
  end
  
  def edit
  end
  
  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render "edit"
    end
  end
  
  def destroy
    @category.destroy
    redirect_to categories_path
  end
  
  private
  
  def set_category
    @category = Category.find(params[:id])
  end
  
  def category_params
    params.require(:category).permit(name)
  ends
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      flash[:alart] = "is too short (minimum is 2 characters)"
      @users = User.all
      render "edit"
    end
  end

  def create
    @user = User.new(user_params)
    if @usre.save
      redirect_to usre_path(@user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面に遷移できません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="flash">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/b0e79b9344.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b0e79b9344.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path,class:"navbar-brand" do %>
            Bookers
          <% end %>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
              <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
                <ul class="navbar-nav ml-auto">
                  <li>
                  <% if user_signed_in? %>
                    <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
                      <i class="fas fa-home"></i>Home
                    <% end %>
                  </li>
                  <li>
                  <%= link_to users_path,class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                  </li>
                  <li>
                  <%= link_to books_path,class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i>Books
                  <% end %>
                  </li>
                  <li>
                  <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                  </li>
                  <% else %>
                  <li>
                  <%= link_to root_path,class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                  </li>
                  <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                  </li>
                  <li>
                  <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                  </li>
                  <li>
                  <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                  </li>
                  <% end %>
                </ul>
              </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/flash' %>
     <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>Copy Right Infratop.ink</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>